# Generated by Django 3.2.9 on 2021-12-03 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titre')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('type_project', models.CharField(choices=[('NON RENSEIGNÉ', 'Non Renseigne'), ('BACK-END', 'Back End'), ('FRONT-END', 'Front End'), ('IOS', 'Ios'), ('ANDROID', 'Android')], default='NON RENSEIGNÉ', max_length=20, verbose_name='Type')),
                ('author_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Liste des projets créés',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titre')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('priority', models.CharField(choices=[('NON RENSEIGNÉ', 'Non Renseigne'), ('ÉLEVÉE', 'Élevée'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], default='NON RENSEIGNÉ', max_length=20, verbose_name='Priorité')),
                ('tag', models.CharField(choices=[('NON RENSEIGNÉ', 'Non Renseigne'), ('BUG', 'Bug'), ('AMÉLIORATION', 'Amélioration'), ('TÂCHE', 'Tâche')], default='NON RENSEIGNÉ', max_length=20, verbose_name='Balise')),
                ('status', models.CharField(choices=[('À FAIRE', 'À Faire'), ('EN COURS', 'En Cours'), ('TÉRMINÉ', 'Términé')], default='À FAIRE', max_length=20, verbose_name='Status')),
                ('author_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_instances', to=settings.AUTH_USER_MODEL)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='softdesk.projects')),
            ],
            options={
                'verbose_name': 'Problème notifié',
                'verbose_name_plural': 'Liste des Problèmes notifiés',
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_to_add', models.IntegerField(verbose_name="ID de l'utilisateur à ajouter")),
                ('permission', models.CharField(choices=[('AUTEUR', 'Auteur'), ('CONTRIBUTEUR', 'Contributeur')], default='CONTRIBUTEUR', max_length=20, verbose_name='Permission')),
                ('role', models.CharField(choices=[('AUTEUR', 'Auteur'), ('CONTRIBUTEUR', 'Contributeur')], default='CONTRIBUTEUR', max_length=20, verbose_name='Rôle')),
                ('project_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='softdesk.projects')),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Liste des contributions',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('author_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_instances', to=settings.AUTH_USER_MODEL)),
                ('parent_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='softdesk.issues')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Liste des commentaires',
            },
        ),
    ]
