# Generated by Django 3.2.9 on 2021-12-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributors',
            name='user_id_to_add',
        ),
    ]
