# Generated by Django 3.2.9 on 2021-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_remove_contributors_user_id_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('CONTRIBUTEUR', 'Contributeur'), ('AUTEUR', 'Auteur')], max_length=20, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('CONTRIBUTEUR', 'Contributeur'), ('AUTEUR', 'Auteur')], max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('NON RENSEIGNÉ', 'Non Renseigne'), ('ÉLEVÉE', 'Élevée'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('À FAIRE', 'À Faire'), ('EN COURS', 'En Cours'), ('TÉRMINÉ', 'Términé')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('NON RENSEIGNÉ', 'Non Renseigne'), ('BUG', 'Bug'), ('AMÉLIORATION', 'Amélioration'), ('TÂCHE', 'Tâche')], max_length=20, verbose_name='Balise'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type_project',
            field=models.CharField(choices=[('NON RENSEIGNÉ', 'Non Renseigne'), ('BACK-END', 'Back End'), ('FRONT-END', 'Front End'), ('IOS', 'Ios'), ('ANDROID', 'Android')], max_length=20, verbose_name='Type'),
        ),
    ]
